name: Code Build

on:
  workflow_call:
    # inputs:
    #   version:
    #     type: string
    #     description: 'Node.js version'
    #     required: true
    #     default: '18.x'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "18.x", "20.x" ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.version}}
        cache-dependency-path: "package-lock.json"
        check-latest: true

    - name: Install the dependencies
      run: npm ci

    - name: Lint the Code
      run: npm run lint
