name: "Main Work Flow"

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - dev-ops

jobs:
  docker-build-scan:
    name: Docker Build and Scan
    uses: ./.github/workflows/docker-build-scan.yaml
    permissions:
      # required for all workflows
      security-events: write
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
